version: "3.9"

services:

    db:
      image: postgres:10-alpine
      volumes:
        - pg_data=/var/lib/postgresql/data/pgdata
      environment:
        - POSTGRES_DB=peaks
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=P34ks

    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./peaks:/code
      ports:
        - "8000:8000"
      environment
        - DB_HOST=db
        - DB_name=peaks
        - DB_USER=postgres
        - DB_PASS=P34ks      
      depends_on:
        - db

volumes:
  mysql_data:

